### PR TITLE
Python-Saucelab integration example

### PR DESCRIPTION
**Pull request by Abhimaniu**
# Description

Added a new file, for demonstrating, how to run dependant selenium test cases on single browser session on sauce lab cloud through python.

Fixes # 11

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Created a sauce lab account and tested these changes on that account through pytest cli.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by surevs** [comment]
@obannak  - can you please close the review on this PR?

**Comment by Abhimaniu** [comment]
@obannak - Any updates on the review?

**Comment by obannak** [comment]
looks good, approving the same

**Comment by surevs** [comment]
Could someone please resolve the conflicts so that I can proceed with merge

**Comment by obannak** [comment]
Sure Revanth, I will resolve conflicts.

**Pull request merged**
